"""add parent_id to categories

Revision ID: 58ed6eb82e89
Revises: 133bc3cf481c
Create Date: 2025-12-28 00:41:02.777841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58ed6eb82e89'
down_revision: Union[str, Sequence[str], None] = '133bc3cf481c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    op.add_column('categories', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('categories_name_key'), 'categories', type_='unique')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.create_foreign_key(None, 'categories', 'categories', ['parent_id'], ['id'], ondelete='RESTRICT')
    op.add_column('products', sa.Column('brand', sa.String(), nullable=True))
    op.add_column('products', sa.Column('condition', sa.Enum('NUEVO', 'CASI_NUEVO', 'USADO', name='product_condition'), nullable=False))
    op.alter_column('products', 'video',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('products_category_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('products', 'tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_category_id_fkey'), 'products', 'categories', ['category_id'], ['id'])
    op.alter_column('products', 'video',
               existing_type=sa.String(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('products', 'condition')
    op.drop_column('products', 'brand')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_unique_constraint(op.f('categories_name_key'), 'categories', ['name'])
    op.drop_column('categories', 'parent_id')
    op.create_table('tags',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('tags_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='tags_pkey'),
    sa.UniqueConstraint('name', name='tags_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_table('product_tags',
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('product_tags_product_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('product_tags_tag_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'tag_id', name=op.f('product_tags_pkey'))
    )
    # ### end Alembic commands ###
